### ISSUE TITLE
Better Security for Login

### ISSUE THREAD

**Issue by jxsl13** [CytraL/twp#10]
If this web panel is accessible through the internet, I think that maybe someone will want to try to get access without you wanting them to get access.
As I see you can easily check out as many login/password combinations as you want.
It would be preferable to have some cool down after the third login try like 10 seconds, after 5 false tries maybe 1 minute and after 10 false tries 1 hour.
I don't know if it would be best with cookies & ip logging or whatever would be best to realize that and to prevent brute force attacks.

**Comment by CytraL** [comment]
I will use IP... can be used for fuck ppl... but best that nothing xD and that cookies.
