### ISSUE TITLE
Could you add the needed zip/tar.gz file structure to the readme.md

### ISSUE THREAD

**Issue by jxsl13** [CytraL/twp#11]
Could you add the needed zip/tar.gz file structure to the readme.md,  so that the webpanel  understands that what I upload is actually the mod files/binary ?
I can't get a server/mod instance running.
Thanks :D

like 
zcatch.zip/tar.gz
- zcatch_folder
- - zcatch_srv 
- - maps
- - - dm1.map
- - mapres
- - - jungle_doodages.png
...

**Comment by CytraL** [comment]
Try with:
- zcatch_folder
- - zcatch_srv
- - data
- - - maps
- - - - dm1.map
- - - mapres
- - - - jungle_doodages.png ...
