### ISSUE TITLE
Secret key commited?

### ISSUE THREAD

**Issue by heinrich5991** [CytraL/twp#12]
It looks like you've commited your secret key, see the top of twp.py.

**Comment by CytraL** [comment]
Yes :\ for now i don't know how generate it.... perhaps i will do a "first start" page where configure admin password and generate this key... perhaps change .conf and only use SQLite...

**Comment by heinrich5991** [comment]
Something like

    try:
        secret_key = open("secret_key").read()
    except FileNotFoundError:
        secret_key = binascii.hexlify(os.urandom(24)).decode()
        open("secret_key", 'w').write(secret_key)

could work.

**Comment by CytraL** [comment]
yeah...finally i do:
```
SECRET_KEY = config.get('global', 'secret', None)
if not SECRET_KEY:
    SECRET_KEY = binascii.hexlify(os.urandom(24)).decode()
    config.set('global', 'secret', SECRET_KEY)
    config.write(open('twp.conf', 'w'))
```

thx ;)
