### ISSUE TITLE
Improve administrative permissions

### ISSUE THREAD

**Issue by CytraL** [CytraL/twp#15]
Change admin concept to "root" concept.
Define admins for specific servers

Requested by jxsl13 & Schwertspize

**Comment by Schwertspize** [comment]
Actually no. (sorry I should have made an issue myself)

My idea is that the admin is able to add new users (just a new instance in the users table) and each record (=user) is either admin or has a list of server (internal ids) on which he has fully access. If you login with that user, you don't see other servers just the ones you have access to. Also you can't register a server by yourself and you can't register a user by yourself.

**Comment by jxsl13** [comment]
it's the same as my issue which got closed, cuz this web panel is not intended to be used the way uptee is used, but only for admin purposes.

**Comment by josephgbr** [comment]
IMO, it would be nice to have "admin" as a superuser (like "root") and to be possible to support 1) users with administrative permissions and 2) users with only read-access
Or without 2), but allow anonymous access to statistics, to see how things are going, like in http://teeworlds-stats.info/

**Comment by CytraL** [comment]
Ok updated issue description :) hope that now i understand properly xDD

**Comment by CytraL** [comment]
@josephgbr for now only like administrative purposes... but in the future i like add a addons system for extend with stuff like this.
