### ISSUE TITLE
Install script support other distros and daemon system...

### ISSUE THREAD

**Issue by CytraL** [CytraL/twp#16]
Improve scripts for work in varius systems..

Requested by Schwertspize

**Comment by josephgbr** [comment]
For a reference of systemd, see [twp.service](https://aur.archlinux.org/cgit/aur.git/tree/twp.service?h=twp) I used in the [AUR package](https://aur.archlinux.org/packages/twp/) i created for Archlinux.

**Comment by CytraL** [comment]
HI josephgbr, thx for the support!!

**Comment by CytraL** [comment]
Ok! the new script candidate: https://gist.github.com/CytraL/e1e3ab5b77c0c90603ca02034a42d9c5

Now detect if hash "systemctl" (systemD)... if not uses systemV.
Can run with: sudo ./install.sh 
or: ./install.sh <USER>

**Comment by Schwertspize** [comment]
@CytraL better now, but I would still prefer it a bit different. 

Like, you execute that script as the user under which it's going to run, the script checks what's installed and then asks you to install them as root (and maybe compose an apt line). And btw, pip can install with the --user flag (pip3). 

Work flow: on github or the page there is a list of dependencies. You run the script eg as user teeworlds, it may complain about missing git or anything. After you install everything (please, all checks run before aborting) you re-run it and it runs pip  and su h as user.

**Comment by CytraL** [comment]
Currently you can do it if have **_sudo_** installed... or using **_su -c "./install.sh $USER"_** with the user that you like use for installation.

Use --user flag with pip... if you install a library why not install for all? if you like something for your particular case, modify the script or create your own script ;)
