### ISSUE TITLE
Manual way of adding server

### ISSUE THREAD

**Issue by Schwertspize** [CytraL/twp#21]
There should be an alternate way of adding servers (eg existing servers) with these options
1. The servers base dir
2. The config the server runs with (default autoexec.cfg)
3. If the server should run as a child of tw
 4.a if yes: binary name
 4.b if no: maybe start/stop command (to integrate in other ways of running the server (could be a command like `kill -9 $(cat $BASEDIR/tw.pid)` or if using daemontools, like me `svc -d (or -u to start) $BASEDIR`
5. Maybe an additional Logfile (maybe add that to twp as well) 

If all these are available, I will consider using twp. (why not?)

**Comment by CytraL** [comment]
I not understand point "3".. run as child of tw?
Why is needed the point "5"?

use autoexec.cfg as default config isn't technically possible... TWP uses configfile like a mark to distinguish between instances of the same mod.

**Comment by Schwertspize** [comment]
Sorry I meant run as child of twp (twp cares about keeping the server online. Intended to just be a tick box, if you don't tick it you say "twp should control the server but some other service (like systemd eg) keep it online" 
With 5 I mean if 3 is ticked, capture all output of the server (= if standard installation) for reading purpose. If 3 is not ticked, specify a command which twp runs (if you want to capture a Logfile, tail -f would do the job) and twp captures all output of THAT command

**Comment by CytraL** [comment]
> if you don't tick it you say "twp should control the server but some other service (like systemd eg) keep it online" 
Currently TWP only need the configuration file for show the server in the panel... if you don't check 'Auto Relaunch if offline' twp only report issues. You can launch/stop the server using other tools... no problem for that :)

> specify a command which twp runs (if you want to capture a Logfile, tail -f would do the job) and twp captures all output of THAT command
If you specify the "logfile" in the config of the server you can see the log by date... if not you know that the file are in "BASE_FOLDER/MOD/logfile.log".
