### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by CytraL** [CytraL/twp#27]
knock! knock!
@josephgbr 

Can update translations?

**Comment by CytraL** [comment]
Ummm best not per now... need finish some stuff that requires new strings..

**Comment by CytraL** [comment]
knock! knock!
@josephgbr

**Comment by josephgbr** [comment]
lol. I notice that you closed before I read, so I did nothing. Don't worry, I'll update asap. If not today, tomorrow.

**Comment by CytraL** [comment]
Yeah, i close it but reopen and close it again and reopen.. xDDD sry :B 

No problem, thanks for your time and translation! ;)

**Comment by CytraL** [comment]
Ok.. i will release 0.3.0 this night.

**Comment by josephgbr** [comment]
Sorry for the delay. I had to debug a ridiculous yet important issue in my update_l10n.sh

**Comment by CytraL** [comment]
OOk! yes i see it... that generates empty files. Nice that now works good :)
