### ISSUE TITLE
Object Based Teeworlds-Mod Implementation

### ISSUE THREAD

**Issue by jxsl13** [CytraL/twp#3]
Every mod could be made into an object with stuff like description, server version, name, coder(s) and so on...
basically this way https://github.com/upTee/upTee/wiki/Mod-format

The possibility to make one config file with a special syntax which is parsed by the  hosting environment and then made into e.g. drop down lists, text fields, password fields, text areas and so on as well as default values preset by the admin.
Basically this way https://github.com/upTee/upTee/wiki/Config-format , but the actual config order of the commands and settings should be kept as they are written in the config file.

Additional commands could be:
#widget:header:"Basic Teeworlds Settings"
This could be used to seperate one category of commands from different ones, like the most basic commands, then teeworlds mod-specific commands and some more specific mod tuning commands.

sv_name "Default Servername" #widget:text #widget:description #widget:type:basic
sv_tune "" #widget:text #widget:description #widget:type:advanced

The most basic categories should be the two categories of basic commands and advanced commands, where the advanced ones should not be shown by default, but either in a different tab or hidden in a kind of spoiler, in order not to overwhelm users, who are not used to those complex commands(e.g. tuning).

In order not to overwhelm users with lots of commands which are not always self-explaining, you could add some kind of maybe javascript effect or something simplier, like a pop-up on mouseover or whatever you think would fit to show a command-specific description.

**Comment by CytraL** [comment]
Interesting... but i think that can be best if include the "config manifest" into a json file... more easy to read..
