### ISSUE TITLE
TWP 0.3.0 won't start

### ISSUE THREAD

**Issue by josephgbr** [CytraL/twp#31]
When trying to start TWP, I get no output, but server won't start. My system is debian 7 x86_64, I already verified folder permissions (set to user twp and group twp) and installed depedencies via "pip".

Also, `python test.py` reports errors (see [full output](https://github.com/CytraL/twp/files/274242/test-error.txt)) in 3rd test, pointing to the following:

> File "/srv/twp/webcontroller/private.py", line 201, in save_server_config
    cfgfile.write(srvcfg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 34-39: ordinal not in range(128)

Please notice that `server/` is empty.

Please help?

**Comment by CytraL** [comment]
try removing 'u' from test.py strings.

go to /srv/twp/twp.conf and change 'DEBUG' param to True. Run the app.. and copy here what happens.... :S

**Comment by CytraL** [comment]
Perhaps is a problem with "stop_server" call... i miss an import on admin.py and can't remove 'mods' :S

**Comment by josephgbr** [comment]
Setting debug to `True `didn't change a thing: still no output and an instance won't start.
The error reported by test.py was related to some special characters in [line 123](https://github.com/CytraL/twp/blob/0.3.0/test.py#L123). Removing 'u' didn't change a thing, but changing "éáçñèö" to non-special character (like 'bla') stopped reporting error - don't if that's expected, though.

**Comment by CytraL** [comment]
umm... you are running "twp.py" or "run.py" in 0.3.0 changed an now need start app with "run.py"

**Comment by josephgbr** [comment]
Oh, I didn't notice this change. Indeed, running `run.py` starts the server without issue.  Since you asked, `locale -a` returns a lot of locales -- no problem there, I assume.
