### ISSUE TITLE
Init script not starting or stopping appropriately

### ISSUE THREAD

**Issue by josephgbr** [CytraL/twp#32]
Environment: debian 7.0, x86_64, TWP 0.3.0, and now I'm using `run.py`:)

**start:**
Without `--background` flag, the init script won't end -- I assume it keep waiting for `run.py` to finish its tasks. When adding `--background` to start-stop-daemon, the init scripts starts TWP and ends itself normally (as expected). Can you please add it to the init script?

**stop:**
I can't seem to stop twp. I notice that since `run.py`, my daemon starts 2 instances:
> twp       8844  4.2  4.7 114356 37576 ?        SNl  13:37   0:00 /usr/bin/python /srv/twp/run.py
> twp       8867  5.4  5.5 232660 43548 ?        SNl  13:37   0:00 /usr/bin/python /srv/twp/run.py

When I run init script to stop the daemon, it kills only the first one (which, by te way, is the PID stored by the init script). It looks like `run.py` is running itself again, which goes out of init script's radar.  Ideas?

**Comment by CytraL** [comment]
Can try with updated install.sh and 0.3.1 branch?

**Comment by josephgbr** [comment]
Working just fine! Thanks!
