### ISSUE TITLE
Unable to set a DDNet server with TWP 

### ISSUE THREAD

**Issue by josephgbr** [CytraL/twp#35]
When trying to set a server from source code, TWP seems to do it successfully. However, no client or server executable is created.
When building set a server from binary tarball, TWP reports URL invalid (maybe due to XZ compressed tarball?)
I've tried with DDNet version 10.1.1.

**Comment by CytraL** [comment]
TWP can't compile source code... but sound like good feature to implement using "git". And yes, TWP can't use LZMA :(

Perhaps in the future...

**Comment by josephgbr** [comment]
It would be nice to display a message to inform that TWO can't compile source code of mods at the moment.

**Comment by CytraL** [comment]
Currently the dialog shows the message "URL to .zip or .tar.gz Teeworlds Package:" ;)

And working on git-compilation feature... I'm thinking how to deal with bam.

**Comment by josephgbr** [comment]
While trying to install mod from Git, I've received the following error "Error: Can't clone git repository!". My log file reports that '-C' is not a valid argument for Git:

> Unknown option: -C

Indeed, your commit has, in [line 423](https://github.com/CytraL/twp/commit/eb191cd8effab39e6f78eff3a06aee79293e5c21#diff-403a0fe752b35ca31100258cae9b1f17R423), "-C" to git command.

**Comment by CytraL** [comment]
What version of git uses? I have 'v2.7.4'

**Comment by josephgbr** [comment]
I have v1.7.0 from Debian Wheezy package. Since it is a VPS, I'll consider a distro upgrade. Thanks.
