### ISSUE TITLE
Administration of user's servers 

### ISSUE THREAD

**Issue by jxsl13** [CytraL/twp#5]
Even if you try to make the interface as self-explaining as possible and as easy to use as possible, there are and will always be people, who get some trouble with complex mods and maybe just don't know how to setup something to work as they want it to work.
So in order to be able to provide proper support for those people, it would be best to be able to set up their servers from the admin account(s).

Great would be of course to have some kind of ticket system, where users could simply go into their server config, push a "help" button, be redirected to a contact form, state their problem and it would be in a ticket queue, which is visible to all administrators as well as the user who opened the ticket.

**Comment by CytraL** [comment]
Users related feature.
