### ISSUE TITLE
Share Teeworlds Server status

### ISSUE THREAD

**Issue by jxsl13** [CytraL/twp#7]
Maybe some kind of possibility to link that server status via an iframe or as a png file on a different website. 
I'd prefer it as png "file" where you have got that simple style of your admin environment as the status png's style and the possibility to change parameters like font color, background color and so on.
Of course it should not work as a server status tool for different servers than those that are hosted there, because that is not its purpose.

**Comment by CytraL** [comment]
First Example....
- Can change gradient color
- Can change server name color
- Can change detail text color

![server banner](http://dl.dropboxusercontent.com/u/30566237/imgs/twp/banner.png)

**Comment by CytraL** [comment]
For 0.1.0 release...
![Banner Creator](http://dl.dropboxusercontent.com/u/30566237/banner-creator.png)
